#!/bin/sh

old=`cat /sys/class/backlight/intel_backlight/brightness`
max=`cat /sys/class/backlight/intel_backlight/max_brightness`
new=`expr $old + $1`

# make sure not to go below 0
if [ $new -lt 100 ]
then
        new=100
fi

# make sure not to go over the maximum brightness
if [ $new -gt $max ]
then
        new=$max
fi

echo $new | tee /sys/class/backlight/intel_backlight/brightness

