#!/bin/sh

network="$(nmcli -g STATE,CONNECTION device status | grep "connected:" | cut -d: -f2)"
if [ -z "$network" ]; then
  network="X"
fi

partitions="$(df -h | grep -e "^/dev/" | grep --invert-match "/boot" | awk '{ printf("%s  %s / %s (%s)\n", $1, $3, $2, $5) }')"

sound_vol="$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))"
date="$(date '+%Y-%m-%d  %H:%M:%S (%a)')"


partition_status=""
IFS=$'\n'
for partition in $partitions; do
  partition_status+="|  $partition  "
done

#
# battery
#
battery=""
battery_dir="/sys/class/power_supply/BAT0"
if [ -d  "$battery_dir" ]; then
  capacity="$(cat $battery_dir/capacity)"
  battery+="$capacity%"
  echo "$battery"

  if [ "$(cat $battery_dir/status)" == "Charging" ]; then
    battery+=" (🔌)"
  elif [ "$(cat $battery_dir/status)" == "Full" ]; then
    battery+=" (Full)"
  fi
else
  battery+="X"
fi

xsetroot -name "$partition_status|  📶 $network  |  🔊 $sound_vol  |  🔋 $battery  |  $date  "

