---
- name: Set fact(st_path)
  set_fact:
    st_path: "{{ ansible_env.HOME }}/git/st"

- name: Git clone st repository (always re-build st)
  git: 
    repo: 'git://git.suckless.org/st'
    dest: "{{ st_path }}"

- name: Copy custom config.h
  copy:
    src: st/config.h
    dest: "{{ st_path }}/config.h"
    force: yes

- name: Make st
  community.general.make:
    chdir: "{{ st_path }}"

- name: Make install st
  community.general.make:
    chdir: "{{ st_path }}"
    target: install
  become: yes

