---
- name: Set fact(dwm_path)
  set_fact:
    dwm_path: "{{ ansible_env.HOME }}/git/dwm"
  tags:
    - dwm

- name: Git clone dwm repository
  git: 
    repo: 'git://git.suckless.org/dwm'
    dest: "{{ dwm_path }}"
  tags:
    - dwm

- name: Copy suctom config.h
  copy:
    src: dwm/config.h
    dest: "{{ dwm_path }}/config.h"
    force: yes
  tags:
    - dwm

- name: Make dwm
  community.general.make:
    chdir: "{{ dwm_path }}"
  tags:
    - dwm

- name: Make install dwm
  community.general.make:
    chdir: "{{ dwm_path }}"
    target: install
  become: yes
  tags:
    - dwm

