---
- name: Install wallpaper packages using pacman
  community.general.pacman:
    name: "{{ wallpaper_packages }}"
    state: present
  become: yes
  tags:
    - wallpaper
    - wallpaper-packages

- name: Copy wallpaper images
  copy:
    src: wallpaper/
    dest: "{{ ansible_env.HOME }}/.wallpaper/"
    force: yes
  tags:
    - wallpaper

