---
# defaults file for arch
common_packages:
  - base
  - base-devel
  - xorg-server
  - xorg-xinit
  - xorg-xset
  - git
  - vim
  - dmenu
  - tree
  - firefox
  - pulseaudio
  - pulseaudio-alsa
  - alsa-utils

wallpaper_packages:
  - feh

font_packages:
  - noto-fonts
  - noto-fonts-cjk

dotfiles:
  - dotfiles/bash_profile
  - dotfiles/bashrc
  - dotfiles/vimrc
  - dotfiles/xinitrc
  - dotfiles/gitconfig

