---
# defaults file for arch
hostname: arch
timezone: Asia/Seoul
locale_gen:
  - en_US.UTF-8
  - en_US
  - ko_KR.EUC-KR
  - ko_KR.UTF-8

common_packages:
  - base
  - base-devel
  - linux-firmware
  - linux-headers
  - xorg-server
  - xorg-xinit
  - xorg-xset
  - xorg-xrandr
  - xorg-xsetroot
  - libxft
  - libxinerama
  - git
  - vim
  - tree
  - firefox
  - pulseaudio
  - pulseaudio-alsa
  - alsa-utils
  - go
  - strace
  - man-db
  - man-pages
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - bluez
  - bluez-utils
  - jq
  - openssh
  - htop

wallpaper_packages:
  - feh

font_packages:
  - noto-fonts
  - noto-fonts-cjk

font_conf:
  - { src: fonts.conf, dest: .config/fontconfig/fonts.conf }

fcitx_packages:
  - fcitx
  - fcitx-hangul

fcitx_conf:
  - { src: fcitx/profile, dest: .config/fcitx/profile }
  - { src: fcitx/fcitx-hangul.config, dest: .config/fcitx/conf/fcitx-hangul.config }

dotfiles:
  - dotfiles/bash_profile
  - dotfiles/bashrc
  - dotfiles/vimrc
  - dotfiles/xinitrc
  - dotfiles/gitconfig

raven_reader:
  # https://github.com/hello-efficiency-inc/raven-reader/releases
  url: https://github.com/hello-efficiency-inc/raven-reader/releases/download/v0.6.6/Raven-Reader-0.6.6.AppImage
  dest: /usr/local/bin/raven-reader
  mode: '0755'
  required_packages:
    - fuse

etc_packages:
  - hugo
  - android-file-transfer
  - notification-daemon
  - libnotify
  - sxiv
  - deepin-screenshot
  - imagemagick
  - filezilla
  - mplayer
  - nnn

