---
# defaults file for arch
common_packages:
  - base
  - base-devel
  - xorg-server
  - xorg-xinit
  - xorg-xset
  - xorg-xrandr
  - libxft
  - libxinerama
  - git
  - vim
  - tree
  - firefox
  - pulseaudio
  - pulseaudio-alsa
  - alsa-utils

wallpaper_packages:
  - feh

font_packages:
  - noto-fonts
  - noto-fonts-cjk

font_conf:
  - { src: fonts.conf, dest: .config/fontconfig/fonts.conf }

fcitx_packages:
  - fcitx
  - fcitx-hangul

fcitx_conf:
  - { src: fcitx/profile, dest: .config/fcitx/profile }
  - { src: fcitx/fcitx-hangul.config, dest: .config/fcitx/conf/fcitx-hangul.config }

dotfiles:
  - dotfiles/bash_profile
  - dotfiles/bashrc
  - dotfiles/vimrc
  - dotfiles/xinitrc
  - dotfiles/gitconfig

