---
- name: Set fact(st_path)
  set_fact:
    st_path: "{{ playbook_dir }}/suckless/st"
  tags:
    - st

- name: Git clone st repository (always re-build st)
  git:
    repo: 'git://git.suckless.org/st'
    dest: "{{ st_path }}"
    force: yes
  tags:
    - st

- name: Copy custom config.h
  copy:
    src: st/config.h
    dest: "{{ st_path }}/config.h"
    force: yes
  tags:
    - st

- name: Make st
  community.general.make:
    chdir: "{{ st_path }}"
  tags:
    - st

- name: Make install st
  community.general.make:
    chdir: "{{ st_path }}"
    target: install
  become: yes
  tags:
    - st

