---
- name: Install common packages using pacman (!! This tasks may takes LONG LONG time !!)
  community.general.pacman:
    name: "{{ common_packages }}"
    state: present
  become: yes
  tags:
    - common-packages
    - common

- name: Copy xorg conf file
  copy:
    src: xorg.conf
    dest: /etc/X11/xorg.conf
    force: yes
    owner: root
    group: root
  become: yes
  tags:
    - common-conf
    - common

