---
- name: Install bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: "{{ ansible_env.HOME }}/.bash-git-prompt"
    depth: 1
    force: yes
  tags:
    - dotfiles

- name: Copy dotfiles
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item | replace('dotfiles/', '.') }}"
    force: yes
  loop: "{{ dotfiles }}"
  tags:
    - dotfiles

