---
- name: Install etc packages using pacman
  community.general.pacman:
    name: "{{ etc_packages }}"
    state: present
  become: yes
  tags:
    - etc-packages
    - etc

- name: Copy my scipts
  copy:
    src: scripts/
    dest: "{{ ansible_env.HOME }}/.local/scripts/"
    mode: "0744"
    force: yes
  tags:
    - scripts
    - etc

- name: set fact (vim-color-theme)
  set_fact:
    vim_color_theme: "{{ ansible_env.HOME }}/.vim/pack/themes/start"
  tags:
    - vim
    - etc

- name: Ensure vim color theme directory exists
  file:
    path: "{{ vim_color_theme }}"
    state: directory
  tags:
    - vim
    - etc

- name: Download color theme
  git:
    repo: https://github.com/dracula/vim.git
    dest: "{{ vim_color_theme }}/dracula"
    force: yes
  tags:
    - vim
    - etc

