---
- name: Install etc packages using pacman
  community.general.pacman:
    name: "{{ etc_packages }}"
    state: present
  become: yes
  tags:
    - etc-packages
    - etc

- name: Copy my scipts
  copy:
    src: scripts/
    dest: "{{ ansible_env.HOME }}/.local/scripts/"
    mode: "0744"
    force: yes
  tags:
    - scripts
    - etc

