---
- name: Install fcitx packages using pacman
  community.general.pacman:
    name: "{{ fcitx_packages }}"
    state: present
  become: yes
  tags:
    - fcitx

- name: Ensure fcitx conf directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/fcitx/conf"
    state: directory
  tags:
    - fcitx

- name: Copy fcitx conf files
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    force: yes
  loop: "{{ fcitx_conf }}"
  tags:
    - fcitx

