---
- name: Install font packages using pacman
  community.general.pacman:
    name: "{{ font_packages }}"
    state: present
  become: yes
  tags:
    - font-packages
    - font

- name: Ensure font conf directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/fcitx/config"
    state: directory
  tags:
    - font-conf
    - font

- name: Copy font conf files
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    force: yes
  loop: "{{ font_conf }}"
  tags:
    - font-conf
    - font

