- name: Install MPD (music player daemon)
  community.general.pacman:
    name: mpd
    state: present
  become: yes
  tags:
    - mpd

- name: Enable / start MPD
  systemd:
    state: started
    name: mpd
    enabled: yes
  become: yes
  tags:
    - mpd

- name: Ensure mpd config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/mpd"
    state: directory
  tags:
    - mpd
    - mpd-config

- name: Copy mpd config file
  copy:
    src: mpd.conf
    dest: "{{ ansible_env.HOME }}/.config/mpd/mpd.conf"
    force: yes
  notify:
    - Restart mpd
  tags:
    - mpd
    - mpd-config


