#
# ~/.bash_profile
#

export PATH="$PATH:$HOME/.local/scripts:$HOME/.local/bin"
export EDITOR='vim'
export TERMINAL='st'
export BROWSER='brave'
export RSS='raven-reader'

[[ -f ~/.bashrc ]] && . ~/.bashrc
