" Syuntax highlighting
filetype plugin on
syntax on


" etc
set laststatus=2
set statusline+=%F
set number
set relativenumber
set hlsearch
set shiftwidth=2


" command alias
command W w
command Wq wq
command Q q


" highlight trailing white space
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/


" indent
filetype indent on


" color
" https://draculatheme.com/vim
packadd! dracula
syntax enable
colorscheme dracula


" NerdTree (close vim if the only window left open is a NERDTree)
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif


" Shortcut
map<C-p> :NERDTreeToggle<CR>

