#!/bin/sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
fcitx &

/usr/lib/notification-daemon-1.0/notification-daemon &

feh --bg-fill --randomize ~/.wallpaper/* &

xset r rate 300 50 &

amixer set Master 50%

while true
do
  sound_vol="$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))"
  date="$(date '+%Y-%m-%d  %H:%M:%S (%a)')"

  xsetroot -name "|  vol: $sound_vol  |  $date  "
  sleep 1s
done &

exec dwm

